dist: jammy
language: erlang
otp_release:
  - 26.1.1
  - 25.3.2.6
  - 24.3.1
#before_install:
#  - sudo apt install rebar
before_script:
script: rebar compile eunit
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "irc.oftc.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
